### ISSUE TITLE
Allow post-event summary/feedback

### ISSUE THREAD

**Issue by punchagan** [thatte-idli-kaal-soup/rsvpapp#11]
It might be nice to allow users to add feedback/summary to an event after it is done.  This would help players use it to keep track of the progress being made, day to day.  Why not allow for pre-event summary too? Use a system like disqus instead of adding our own comment system?

**Comment by vkrishnaswam** [comment]
This will be very useful for the Town Halls that we are planning. Did this come out of that? Or had you planned this earlier?

**Comment by punchagan** [comment]
This issue was created on Apr 7th. :smile:

**Comment by punchagan** [comment]
I've hooked back Zulip messages into the app. So, we are now able to display messages posted in Zulip as comments. I think this is good enough for now.
